### PR TITLE
consumer(kafka): Fix consumer graceful shutdown

### LINKED ISSUE #161: test: TestConsumerDelivery is flaky
`TestConsumerDelivery` is failing inconsistently

Investigate what's wrong

### PR DESCRIPTION
**Pull request by marclop**
## Description

Fixes the consumer graceful shutdown by closing the partition consumers
first, and only after they've all been stopped, close the kgo.Client to
allow the records to be processed before the client is closed.

This fixes some flaky tests and inconsistent shutdown behavior.

## Related issues

Closes #161

### CODE REVIEW

**Review by axw — COMMENTED** [review]
The test is still failing for me when I run it with `-race` in a loop:

`go test -race -run TestConsumerGracefulShutdown -failfast -count=1000`

What is the purpose of this test? It's not clear to me what "graceful shutdown" means, looking at what the test does. Given that we're closing the kgo.Client before the events are known to be consumed, why would we expect them all to be consumed?

File: kafka/consumer.go [hunk 1]
```diff
@@ -165,9 +165,9 @@ func (c *Consumer) Close() error {
 	if !c.closed.CompareAndSwap(false, true) {
```
[the remark this answers is not in the document]
Comment (lahsivjar) [reply kafka/consumer.go:165]: FYI: It was introduced in [this PR](https://github.com/elastic/apm-queue/pull/173) with the expectation that we will return nil if the client is already closed. Maybe what we need is `defer c.closed.Swap(true)`(??)

[the remark this answers is not in the document]
Comment (axw) [reply kafka/consumer.go:165]: :ok_hand:  I think we should generally avoid atomics -- channels are typically more appropriate when trying to communicate between goroutines, to avoid race conditions. If we need an atomic, then we can indeed `defer c.closed.Store(true)`.

[the remark this answers is not in the document]
Comment (lahsivjar) [reply kafka/consumer.go:165]: > Maybe what we need is defer c.closed.Swap(true) if we just want to know if Close succeeded or not

I _think_ this in itself will not be enough, sorry for the confusion. The reason is that after checking with `c.closed.Load()` and before acquiring the read lock, the method `Close` can be called. This I assume will cause `fetch` to fail with a different error than expected `context.Canceled`. I think @axw's suggestion to use channels in this case and interrupt using the channel inside the read lock is better.

**Comment by marclop** [comment]
I've made changes in the consumer to incorporate your feedback, and also fix the not so graceful `consumer.Close()` to wait for the partition consumers to exit.

**Review by endorama — COMMENTED** [review]
I've reviewed the code, I've little context to judge the logic. Tests (with `-race`) are passing.

File: kafka/consumer.go [hunk 2]
```diff
@@ -203,9 +227,16 @@ func (c *Consumer) fetch(ctx context.Context) error {
 		errors.Is(fetches.Err0(), context.DeadlineExceeded) {
 		return context.Canceled
 	}
-	// Acquire the lock after checking if the the context is cancelled and/or
-	// the client is closed.
-	c.mu.RLock()
+	// Acquire the lock after checking if the the context is done.
+	// If the lock cannot be acquired, the consumer is closing,
+	// be closing, in which case, return with context.Cancelled.
+	if !c.mu.TryRLock() {
```
Comment (lahsivjar) [inline kafka/consumer.go:233]: Not a fan of `TryRLock` usage. WDYT about interrupting the `for` loop in `Run` if `c.closed` is closed and in the `Close` method, waiting for `Run` to finish before proceeding to close stuff. Example (only for conveying the intention):

```go
func (c *Consumer) Run(ctx context.Context) error {
	c.mu.Lock()
	select {
	case <-c.running:
		c.mu.Unlock()
		return apmqueue.ErrConsumerAlreadyRunning
	default:
		close(c.running)
	}
	c.mu.Unlock()
        defer close(c.runStopped)
	for {
                select {
                case <-c.closed:
                    return nil // or ErrClosed
                default:
                }
		if err := c.fetch(ctx); err != nil {
			if errors.Is(err, context.Canceled) {
				return nil // Return no error if err == context.Canceled.
			}
			return err
		}
	}
}
```

Then in `Close`:

```go
func (c *Consumer) Close() error {
	c.mu.Lock()
	select {
	case <-c.closed:
	default:
		close(c.closed)
        }
        c.mu.Unlock()
        <-c.runStopped // can choose to pass a context to Close and wait with select

        c.mu.Lock()
        defer c.mu.Unlock()
        // Close all partition consumers first to ensure that there aren't
        // any records being processed while the kgo.Client is being closed.
        // Also ensures that commits can be issued after the records are
        // processed when AtLeastOnceDelivery is configured.
        c.consumer.close() // if this requires to be done only once, we can use a bool flag or maybe set the values to nil if successfully closed
        c.client.Close()
	c.consumer.wg.Wait() // Wait for consumer goroutines to exit.
	return nil
}
```

File: kafka/consumer.go [hunk 3]
```diff
@@ -203,9 +227,16 @@ func (c *Consumer) fetch(ctx context.Context) error {
 		errors.Is(fetches.Err0(), context.DeadlineExceeded) {
 		return context.Canceled
 	}
-	// Acquire the lock after checking if the the context is cancelled and/or
-	// the client is closed.
-	c.mu.RLock()
+	// Acquire the lock after checking if the the context is done.
+	// If the lock cannot be acquired, the consumer is closing,
+	// be closing, in which case, return with context.Cancelled.
```
[the remark this answers is not in the document]
Comment (marclop) [reply kafka/consumer.go:232]: yep, that's correct. I botched this comment a bit. I'll fix it.

**Comment by marclop** [comment]
@lahsivjar @axw I've pushed 1fd36a0, which uses a more solid approach suggested by Andrew. Let me know what you think about it. After this PR is merged, calling `consumer.Close()` will trigger graceful shutdown and either successfully shutdown all the partition consumers within `cfg.ShutdownGracePeriod`, or trigger forceful shutdown after that duration is exceeded.

File: kafka/consumer.go [hunk 4]
```diff
@@ -153,39 +174,80 @@ func NewConsumer(cfg ConsumerConfig) (*Consumer, error) {
...
+		c.mu.Unlock()
 		return apmqueue.ErrConsumerAlreadyRunning
+	default:
+		close(c.running)
 	}
+	// Create a new context from the passed context, used exclusively for
+	// kgo.Client.* calls. c.stopFetch is called by consumer.Close() to
+	// cancel this context as part of the graceful shutdown sequence.
+	var clientCtx context.Context
+	clientCtx, c.stopPoll = context.WithCancel(ctx)
```
Comment (axw) [inline kafka/consumer.go:245]: Because `stopPoll` is only set after `Run` is called, calling `Stop` before `Run` means that the poll context won't be closed. Should we instead start a goroutine that waits for `c.closed` and cancels the context?

File: kafka/consumer.go [hunk 5]
```diff
@@ -153,39 +174,80 @@ func NewConsumer(cfg ConsumerConfig) (*Consumer, error) {
...
+		// the underlying processing context if they aren't stopped in time.
+		select {
+		case <-time.After(c.cfg.ShutdownGracePeriod): // Timeout
+			c.forceClose(fmt.Errorf(
+				"consumer: close: timeout waiting for consumers to stop (%s)",
+				c.cfg.ShutdownGracePeriod.String(),
+			))
+		case <-stopped: // Stopped within c.cfg.ShutdownGracePeriod.
+		}
+		c.client.Close() // Last, close the `kgo.Client`
```
Comment (axw) [inline kafka/consumer.go:218]: Should we do this as a defer, after the `close(c.closed)`? Or does it need to happen before we wait for the waitgroup?

File: kafka/consumer.go [hunk 6]
```diff
@@ -153,39 +174,80 @@ func NewConsumer(cfg ConsumerConfig) (*Consumer, error) {
...
+	}
+	c.consumer.wg.Wait() // Wait for consumer goroutines to exit.
```
Comment (axw) [inline kafka/consumer.go:220]: Maybe do this in a defer, and then we can early return if we hit `case <-c.closed`

File: kafka/consumer.go [hunk 7]
```diff
@@ -322,23 +353,97 @@ func (c *consumer) assigned(ctx context.Context, client *kgo.Client, assigned ma
...
+		case <-ctx.Done(): // Consumer.Run(ctx) context.
+			err = ctx.Err()
+		case <-c.ctx.Done(): // Forceful cancellation context.
+			err = c.ctx.Err()
+		}
+		// When using AtMostOnceDelivery, if the context is cancelled between
+		// PollRecords and this line, records will be lost.
+		if c.delivery == apmqueue.AtMostOnceDeliveryType {
+			c.logWarn(err, ftp)
+		}
```
Comment (axw) [inline kafka/consumer.go:427]:
```suggestion
		if err != nil {
			if c.delivery == apmqueue.AtMostOnceDeliveryType {
				c.logWarn(err, ftp)
			}
		}
```

File: kafka/consumer.go [hunk 8]
```diff
@@ -322,23 +353,97 @@ func (c *consumer) assigned(ctx context.Context, client *kgo.Client, assigned ma
...
+}
+
 // Implement the kgo.Hook that allows injecting the kgo.Client context that is
 // received on partition assignment.
 func (c *consumer) OnFetchRecordBuffered(r *kgo.Record) {
 	// Inject the context so records's context have cancellation.
 	if r.Context == nil {
-		c.mu.RLock()
-		defer c.mu.RUnlock()
 		// NOTE(marclop) Using the kgo.Client context may result in records
```
Comment (axw) [inline kafka/consumer.go:447]: We're not using it now, right? Should we update this comment?

File: kafka/consumer_test.go [hunk 9]
```diff
@@ -421,26 +438,44 @@ func TestConsumerGracefulShutdown(t *testing.T) {
...
+		// Assert the consumer error.
+		switch dt {
+		case apmqueue.AtMostOnceDeliveryType:
+			if consumerErr != nil {
+				assert.Equal(t, ErrCommitFailed, consumerErr)
+			}
+		case apmqueue.AtLeastOnceDeliveryType:
+			assert.NoError(t, consumerErr)
+		}
+		assert.GreaterOrEqual(t, processed.Load(), int32(1)) //  Ensure that at least one record is processed.
```
Comment (axw) [inline kafka/consumer_test.go:478]: Isn't the objective of the test to ensure both records are processed?

File: kafka/consumer_test.go [hunk 10]
```diff
@@ -421,26 +438,44 @@ func TestConsumerGracefulShutdown(t *testing.T) {
...
+		case <-time.After(time.Second):
+			t.Fatal("timed out waiting for consumer to exit")
+		}
+
+		// Assert the consumer error.
+		switch dt {
+		case apmqueue.AtMostOnceDeliveryType:
+			if consumerErr != nil {
+				assert.Equal(t, ErrCommitFailed, consumerErr)
+			}
```
Comment (axw) [inline kafka/consumer_test.go:474]: Should this error be consistent/deterministic?

**Review by axw — COMMENTED** [review]
Thanks, I think this is looking good.

File: kafka/consumer.go (hunk 5 above)
Comment (marclop) [reply kafka/consumer.go:218]: I suppose it can be done as a defer, but it seemed more appropriate to keep it outside of the defer just to be able to visualize the order of calls more easily. I can add it in a defer after `close(c.closed)` if you think that's better.

File: kafka/consumer.go (hunk 4 above)
Comment (marclop) [reply kafka/consumer.go:245]: sorry, but I'm afraid I don't follow. The `clientCtx` is only used if `Run()` is called, otherwise it's not used. `c.stopPoll` is set to an empty function and on close would be a no-op.

Comment (axw) [reply kafka/consumer.go:245]:
```go
consumer.Close()
consumer.Run() <- clientCtx is not cancelled because Run was called after Close returned
```

I suppose it doesn't matter though, because Close will close the kgo.Client, causing fetch to return context.Canceled, breaking the loop.

File: kafka/consumer.go (hunk 5 above)
Comment (axw) [reply kafka/consumer.go:218]: I'm mildly concerned that we might update the code and introduce a code path that would lead to the kgo.Client being left open. I'll leave it to your judgement, just a passing thought.

File: kafka/consumer_test.go (hunk 9 above)
Comment (marclop) [reply kafka/consumer_test.go:478]: fixed!

File: kafka/consumer_test.go (hunk 10 above)
Comment (marclop) [reply kafka/consumer_test.go:474]: correct, fixed.

File: kafka/consumer.go (hunk 8 above)
Comment (marclop) [reply kafka/consumer.go:447]: done

**Review by axw — APPROVED** [review]
