### PR TITLE
consumer(kafka): Fix close deadlock, update errors

### LINKED ISSUE #147: consistent behaviour on shutdown
The two providers have different behaviours on shutdown 

Add a test to ensure the behaviour is consistent

### LINKED ISSUE #157: kafka: deadlock when closing consumer without canceling context
kafka consumer Run method will block forever unless the context is canceled.

Trying to close the consumer with `consumer.Close` will block forever. 

This only happens with the Kafka consumer. Pubsublite is not affected.

To reproduce: `cd systemtest && go test -v -run=TestShutdown/Kafka/close`

consumer will block at: https://github.com/elastic/apm-queue/blob/e48ac80251203194fe79626b14749455d5f290d8/kafka/consumer.go#L189

The close method will block trying to acquire the lock.

### PR DESCRIPTION
**Pull request by marclop**
## Description
Updates the `kafka.Consumer` to behave like the `pubsublite.Consumer`. This includes:

- Returning a `nil` error after the context is cancelled, or the client is closed.
- Returning an error if the consumer has already been started.

## Related issues

Closes #157 
Closes #147

### CODE REVIEW

File: kafka/consumer.go [hunk 1]
```diff
@@ -182,20 +197,18 @@ func (c *Consumer) Run(ctx context.Context) error {
...
-	}
-	if errors.Is(fetches.Err0(), context.Canceled) ||
+	if fetches.IsClientClosed() ||
+		errors.Is(fetches.Err0(), context.Canceled) ||
 		errors.Is(fetches.Err0(), context.DeadlineExceeded) {
-		return fmt.Errorf("context done: %w", fetches.Err0())
+		return context.Canceled
 	}
+	// Acquire the lock after checking if the the context is cancelled and/or
+	// the client is closed.
```
Comment (kruskall) [inline kafka/consumer.go:209]: **issue**: I don't think we can do this. What happens if the context is canceled or the client is closed before we acquire the lock but after the records were polled ? This is also making the previous if not safe for concurrent usage as the client could be closed after the `IsClientClosed` is called.

**Review by kruskall — CHANGES_REQUESTED** [review]

File: kafka/consumer.go (hunk 1 above)
Comment (marclop) [reply kafka/consumer.go:209]: > I don't think we can do this. What happens if the context is canceled or the client is closed before we acquire the lock but after the records were polled ? 

If the context is cancelled before the lock is acquired, the call on line 217 will fail for `AtMostOnceDelivery`, and the function will return then. No records will be lost since the commit for the fetched offsets will have failed.

If the context is cancelled between line 228 and 240, the records will be lost, since `AtMostOnceDelivery` has that caveat. This is no different with the lock acquired at the top of the function, before `PollRecords` is called, or after.

The locking doesn't prevent the context from being cancelled at any point in the execution flow.

> This is also making the previous if not safe for concurrent usage as the client could be closed after the IsClientClosed is called.

Why would closing the `kgo.Client` make calls to it not safe? The client can be called at any time, and the `kgo.Client` is safe for concurrent use. The client can be closed at any time while other methods are called, and is within the intended use scope.

File: kafka/consumer.go [hunk 2]
```diff
@@ -149,31 +151,44 @@ func NewConsumer(cfg ConsumerConfig) (*Consumer, error) {
...
 //
 // To shut down the consumer, cancel the context, or call consumer.Close().
+// If called more than once, returns `apmqueue.ErrConsumerAlreadyRunning`.
 func (c *Consumer) Run(ctx context.Context) error {
+	select {
+	case <-c.running:
+		return apmqueue.ErrConsumerAlreadyRunning
+	default:
+		close(c.running)
+	}
```
Comment (lahsivjar) [inline kafka/consumer.go:185]: This can lead to panic due to multiple close on a channel if `Run` is called multiple times in quick succession. As an alternative what do you think about using `atomic.Bool` with its `CompareAndSwap` operation:

```suggestion
        // c.running is defined as an atomic.Bool
	if !c.running.CompareAndSwap(false, true) {
	        return apmqueue.ErrConsumerAlreadyRunning
	}
```

File: kafka/consumer.go [hunk 3]
```diff
@@ -149,31 +151,44 @@ func NewConsumer(cfg ConsumerConfig) (*Consumer, error) {
...
 // Close the consumer, blocking until all partition consumers are stopped.
 func (c *Consumer) Close() error {
-	c.mu.Lock()
-	defer c.mu.Unlock()
-	// Since we take the full lock when closing, there's no need to explicitly
-	// allow rebalances since polls aren't concurrent with Close().
-	c.client.Close()
-	c.consumer.wg.Wait() // Wait for all the goroutines to exit.
+	select {
+	case <-c.closed:
```
Comment (lahsivjar) [inline kafka/consumer.go:163]: For `c.closed` also we can use an `atomic.Bool` as for `c.running`, however, there is no panic in this case.

File: kafka/consumer.go (hunk 1 above)
Comment (kruskall) [reply kafka/consumer.go:209]: TIL! Thanks for the explanation! bow

My only other concern would be that the consumer is not guaranteed to return nil on shutdown. For example, in one of the case you mentioned:

    If the context is cancelled before the lock is acquired, the call on line 217 will fail for AtMostOnceDelivery, and the function will return then.

the consumer would return ErrCommitFailed. WDYT ?

Comment (marclop) [reply kafka/consumer.go:209]: I think that's a legitimate error, since in that case, we may want to re-create the consumer, rather than an entire process.

**Review by kruskall — APPROVED** [review]

File: kafka/consumer.go (hunk 3 above)
Comment (marclop) [reply kafka/consumer.go]: Fixed in 9308bfe

**Review by lahsivjar — APPROVED** [review]
